[mypy]
strict = True
ignore_missing_imports = True
mypy_path = src
warn_unused_ignores = False

# Suppress errors for libraries without stubs
[mypy-yaml.*]
ignore_missing_imports = True

[mypy-dbus.*]
ignore_missing_imports = True

[mypy-dbusmock.*]
ignore_missing_imports = True

[mypy-apprise.*]
ignore_missing_imports = True

[mypy-jinja2.*]
ignore_missing_imports = True
